[build]
  command = "npm run build"
  publish = "build"  # Adjust this based on your actual build folder
  functions = "netlify/functions"  # Adjust the function folder path as needed

[context.production.environment]
  NODE_ENV = "production"
